exports.languages = [
  {
    code: "aa",
    EnglishName: "Afar",
    direction: "ltr",
    localName: "Afar",
  },
  {
    code: "ab",
    EnglishName: "Abkhazian",
    direction: "ltr",
    localName: "Аҧсуа",
  },
  {
    code: "af",
    EnglishName: "Afrikaans",
    direction: "ltr",
    localName: "Afrikaans",
  },
  {
    code: "ak",
    EnglishName: "Akan",
    direction: "ltr",
    localName: "Akana",
  },
  {
    code: "als",
    EnglishName: "Alemannic",
    direction: "ltr",
    localName: "Alemannisch",
  },
  {
    code: "am",
    EnglishName: "Amharic",
    direction: "ltr",
    localName: "አማርኛ",
  },
  {
    code: "an",
    EnglishName: "Aragonese",
    direction: "ltr",
    localName: "Aragonés",
  },
  {
    code: "ang",
    EnglishName: "Angal",
    direction: "ltr",
    localName: "Angal Heneng",
  },
  {
    code: "ang",
    EnglishName: "Anglo-Saxon / Old English",
    direction: "ltr",
    localName: "Englisc",
  },
  {
    code: "ar",
    EnglishName: "Arabic",
    direction: "rtl",
    localName: "العربية",
  },
  {
    code: "arc",
    EnglishName: "Aramaic",
    direction: "rtl",
    localName: "ܣܘܪܬ",
  },
  {
    code: "as",
    EnglishName: "Assamese",
    direction: "ltr",
    localName: "অসমীয়া",
  },
  {
    code: "ast",
    EnglishName: "Asturian",
    direction: "ltr",
    localName: "Asturianu",
  },
  {
    code: "av",
    EnglishName: "Avar",
    direction: "ltr",
    localName: "Авар",
  },
  {
    code: "awa",
    EnglishName: "Awadhi",
    direction: "ltr",
    localName: "Awadhi",
  },
  {
    code: "ay",
    EnglishName: "Aymara",
    direction: "ltr",
    localName: "Aymar",
  },
  {
    code: "az",
    EnglishName: "Azerbaijani",
    direction: "ltr",
    localName: "Azərbaycanca / آذربايجان",
  },
  {
    code: "ba",
    EnglishName: "Bashkir",
    direction: "ltr",
    localName: "Башҡорт",
  },
  {
    code: "bar",
    EnglishName: "Bavarian",
    direction: "ltr",
    localName: "Boarisch",
  },
  {
    code: "bat-smg",
    EnglishName: "Samogitian",
    direction: "ltr",
    localName: "Žemaitėška",
  },
  {
    code: "bcl",
    EnglishName: "Bikol",
    direction: "ltr",
    localName: "Bikol Central",
  },
  {
    code: "be",
    EnglishName: "Belarusian",
    direction: "ltr",
    localName: "Беларуская",
  },
  {
    code: "be-x-old",
    EnglishName: "Belarusian (Taraškievica)",
    direction: "ltr",
    localName: "Беларуская (тарашкевіца)",
  },
  {
    code: "bg",
    EnglishName: "Bulgarian",
    direction: "ltr",
    localName: "Български",
  },
  {
    code: "bh",
    EnglishName: "Bihari",
    direction: "ltr",
    localName: "भोजपुरी",
  },
  {
    code: "bi",
    EnglishName: "Bislama",
    direction: "ltr",
    localName: "Bislama",
  },
  {
    code: "bm",
    EnglishName: "Bambara",
    direction: "ltr",
    localName: "Bamanankan",
  },
  {
    code: "bn",
    EnglishName: "Bengali",
    direction: "ltr",
    localName: "বাংলা",
  },
  {
    code: "bo",
    EnglishName: "Tibetan",
    direction: "ltr",
    localName: "བོད་ཡིག / Bod skad",
  },
  {
    code: "bpy",
    EnglishName: "Bishnupriya Manipuri",
    direction: "ltr",
    localName: "ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী",
  },
  {
    code: "br",
    EnglishName: "Breton",
    direction: "ltr",
    localName: "Brezhoneg",
  },
  {
    code: "brx",
    EnglishName: "Boro",
    direction: "ltr",
    localName: "बड़",
  },
  {
    code: "bs",
    EnglishName: "Bosnian",
    direction: "ltr",
    localName: "Bosanski",
  },
  {
    code: "bug",
    EnglishName: "Buginese",
    direction: "ltr",
    localName: "ᨅᨔ ᨕᨘᨁᨗ / Basa Ugi",
  },
  {
    code: "bxr",
    EnglishName: "Buriat (Russia)",
    direction: "ltr",
    localName: "Буряад хэлэн",
  },
  {
    code: "ca",
    EnglishName: "Catalan",
    direction: "ltr",
    localName: "Català",
  },
  {
    code: "cdo",
    EnglishName: "Min Dong Chinese",
    direction: "ltr",
    localName: "Mìng-dĕ̤ng-ngṳ̄ / 閩東語",
  },
  {
    code: "ce",
    EnglishName: "Chechen",
    direction: "ltr",
    localName: "Нохчийн",
  },
  {
    code: "ceb",
    EnglishName: "Cebuano",
    direction: "ltr",
    localName: "Sinugboanong Binisaya",
  },
  {
    code: "ch",
    EnglishName: "Chamorro",
    direction: "ltr",
    localName: "Chamoru",
  },
  {
    code: "cho",
    EnglishName: "Choctaw",
    direction: "ltr",
    localName: "Choctaw",
  },
  {
    code: "chr",
    EnglishName: "Cherokee",
    direction: "ltr",
    localName: "ᏣᎳᎩ",
  },
  {
    code: "chy",
    EnglishName: "Cheyenne",
    direction: "ltr",
    localName: "Tsetsêhestâhese",
  },
  {
    code: "ckb",
    EnglishName: "Kurdish (Sorani)",
    direction: "rtl",
    localName: "کوردی",
  },
  {
    code: "co",
    EnglishName: "Corsican",
    direction: "ltr",
    localName: "Corsu",
  },
  {
    code: "cr",
    EnglishName: "Cree",
    direction: "ltr",
    localName: "Nehiyaw",
  },
  {
    code: "cs",
    EnglishName: "Czech",
    direction: "ltr",
    localName: "Česky",
  },
  {
    code: "csb",
    EnglishName: "Kashubian",
    direction: "ltr",
    localName: "Kaszëbsczi",
  },
  {
    code: "cu",
    EnglishName: "Old Church Slavonic / Old Bulgarian",
    direction: "ltr",
    localName: "словѣньскъ / slověnĭskŭ",
  },
  {
    code: "cv",
    EnglishName: "Chuvash",
    direction: "ltr",
    localName: "Чăваш",
  },
  {
    code: "cy",
    EnglishName: "Welsh",
    direction: "ltr",
    localName: "Cymraeg",
  },
  {
    code: "da",
    EnglishName: "Danish",
    direction: "ltr",
    localName: "Dansk",
  },
  {
    code: "de",
    EnglishName: "German",
    direction: "ltr",
    localName: "Deutsch",
  },
  {
    code: "diq",
    EnglishName: "Dimli",
    direction: "ltr",
    localName: "Zazaki",
  },
  {
    code: "dsb",
    EnglishName: "Lower Sorbian",
    direction: "ltr",
    localName: "Dolnoserbski",
  },
  {
    code: "dv",
    EnglishName: "Divehi",
    direction: "rtl",
    localName: "ދިވެހިބަސް",
  },
  {
    code: "dz",
    EnglishName: "Dzongkha",
    direction: "ltr",
    localName: "རྫོང་ཁ",
  },
  {
    code: "ee",
    EnglishName: "Ewe",
    direction: "ltr",
    localName: "Ɛʋɛ",
  },
  {
    code: "el",
    EnglishName: "Greek",
    direction: "ltr",
    localName: "Ελληνικά",
  },
  {
    code: "en",
    EnglishName: "English",
    direction: "ltr",
    localName: "English",
  },
  {
    code: "eo",
    EnglishName: "Esperanto",
    direction: "ltr",
    localName: "Esperanto",
  },
  {
    code: "es",
    EnglishName: "Spanish",
    direction: "ltr",
    localName: "Español",
  },
  {
    code: "et",
    EnglishName: "Estonian",
    direction: "ltr",
    localName: "Eesti",
  },
  {
    code: "eu",
    EnglishName: "Basque",
    direction: "ltr",
    localName: "Euskara",
  },
  {
    code: "ext",
    EnglishName: "Extremaduran",
    direction: "ltr",
    localName: "Estremeñu",
  },
  {
    code: "fa",
    EnglishName: "Persian",
    direction: "rtl",
    localName: "فارسی",
  },
  {
    code: "ff",
    EnglishName: "Peul",
    direction: "ltr",
    localName: "Fulfulde",
  },
  {
    code: "fi",
    EnglishName: "Finnish",
    direction: "ltr",
    localName: "Suomi",
  },
  {
    code: "fiu-vro",
    EnglishName: "Võro",
    direction: "ltr",
    localName: "Võro",
  },
  {
    code: "fj",
    EnglishName: "Fijian",
    direction: "ltr",
    localName: "Na Vosa Vakaviti",
  },
  {
    code: "fo",
    EnglishName: "Faroese",
    direction: "ltr",
    localName: "Føroyskt",
  },
  {
    code: "fr",
    EnglishName: "French",
    direction: "ltr",
    localName: "Français",
  },
  {
    code: "frp",
    EnglishName: "Arpitan / Franco-Provençal",
    direction: "ltr",
    localName: "Arpitan / francoprovençal",
  },
  {
    code: "fur",
    EnglishName: "Friulian",
    direction: "ltr",
    localName: "Furlan",
  },
  {
    code: "fy",
    EnglishName: "West Frisian",
    direction: "ltr",
    localName: "Frysk",
  },
  {
    code: "ga",
    EnglishName: "Irish",
    direction: "ltr",
    localName: "Gaeilge",
  },
  {
    code: "gan",
    EnglishName: "Gan Chinese",
    direction: "ltr",
    localName: "贛語",
  },
  {
    code: "gbm",
    EnglishName: "Garhwali",
    direction: "ltr",
    localName: "गढ़वळी",
  },
  {
    code: "gd",
    EnglishName: "Scottish Gaelic",
    direction: "ltr",
    localName: "Gàidhlig",
  },
  {
    code: "gil",
    EnglishName: "Gilbertese",
    direction: "ltr",
    localName: "Taetae ni kiribati",
  },
  {
    code: "gl",
    EnglishName: "Galician",
    direction: "ltr",
    localName: "Galego",
  },
  {
    code: "gn",
    EnglishName: "Guarani",
    direction: "ltr",
    localName: "Avañe'ẽ",
  },
  {
    code: "got",
    EnglishName: "Gothic",
    direction: "ltr",
    localName: "gutisk",
  },
  {
    code: "gu",
    EnglishName: "Gujarati",
    direction: "ltr",
    localName: "ગુજરાતી",
  },
  {
    code: "gv",
    EnglishName: "Manx",
    direction: "ltr",
    localName: "Gaelg",
  },
  {
    code: "ha",
    EnglishName: "Hausa",
    direction: "rtl",
    localName: "هَوُسَ",
  },
  {
    code: "hak",
    EnglishName: "Hakka Chinese",
    direction: "ltr",
    localName: "客家語/Hak-kâ-ngî",
  },
  {
    code: "haw",
    EnglishName: "Hawaiian",
    direction: "ltr",
    localName: "Hawai`i",
  },
  {
    code: "he",
    EnglishName: "Hebrew",
    direction: "rtl",
    localName: "עברית",
  },
  {
    code: "hi",
    EnglishName: "Hindi",
    direction: "ltr",
    localName: "हिन्दी",
  },
  {
    code: "ho",
    EnglishName: "Hiri Motu",
    direction: "ltr",
    localName: "Hiri Motu",
  },
  {
    code: "hr",
    EnglishName: "Croatian",
    direction: "ltr",
    localName: "Hrvatski",
  },
  {
    code: "ht",
    EnglishName: "Haitian",
    direction: "ltr",
    localName: "Krèyol ayisyen",
  },
  {
    code: "hu",
    EnglishName: "Hungarian",
    direction: "ltr",
    localName: "Magyar",
  },
  {
    code: "hy",
    EnglishName: "Armenian",
    direction: "ltr",
    localName: "Հայերեն",
  },
  {
    code: "hz",
    EnglishName: "Herero",
    direction: "ltr",
    localName: "Otsiherero",
  },
  {
    code: "ia",
    EnglishName: "Interlingua",
    direction: "ltr",
    localName: "Interlingua",
  },
  {
    code: "id",
    EnglishName: "Indonesian",
    direction: "ltr",
    localName: "Bahasa Indonesia",
  },
  {
    code: "ie",
    EnglishName: "Interlingue",
    direction: "ltr",
    localName: "Interlingue",
  },
  {
    code: "ig",
    EnglishName: "Igbo",
    direction: "ltr",
    localName: "Igbo",
  },
  {
    code: "ii",
    EnglishName: "Sichuan Yi",
    direction: "ltr",
    localName: "ꆇꉙ / 四川彝语",
  },
  {
    code: "ik",
    EnglishName: "Inupiak",
    direction: "ltr",
    localName: "Iñupiak",
  },
  {
    code: "ilo",
    EnglishName: "Ilokano",
    direction: "ltr",
    localName: "Ilokano",
  },
  {
    code: "inh",
    EnglishName: "Ingush",
    direction: "ltr",
    localName: "ГӀалгӀай",
  },
  {
    code: "io",
    EnglishName: "Ido",
    direction: "ltr",
    localName: "Ido",
  },
  {
    code: "is",
    EnglishName: "Icelandic",
    direction: "ltr",
    localName: "Íslenska",
  },
  {
    code: "it",
    EnglishName: "Italian",
    direction: "ltr",
    localName: "Italiano",
  },
  {
    code: "iu",
    EnglishName: "Inuktitut",
    direction: "ltr",
    localName: "ᐃᓄᒃᑎᑐᑦ",
  },
  {
    code: "ja",
    EnglishName: "Japanese",
    direction: "ltr",
    localName: "日本語",
  },
  {
    code: "jbo",
    EnglishName: "Lojban",
    direction: "ltr",
    localName: "Lojban",
  },
  {
    code: "jv",
    EnglishName: "Javanese",
    direction: "ltr",
    localName: "Basa Jawa",
  },
  {
    code: "ka",
    EnglishName: "Georgian",
    direction: "ltr",
    localName: "ქართული",
  },
  {
    code: "kg",
    EnglishName: "Kongo",
    direction: "ltr",
    localName: "KiKongo",
  },
  {
    code: "ki",
    EnglishName: "Kikuyu",
    direction: "ltr",
    localName: "Gĩkũyũ",
  },
  {
    code: "kj",
    EnglishName: "Kuanyama",
    direction: "ltr",
    localName: "Kuanyama",
  },
  {
    code: "kk",
    EnglishName: "Kazakh",
    direction: "ltr",
    localName: "Қазақша",
  },
  {
    code: "kl",
    EnglishName: "Greenlandic",
    direction: "ltr",
    localName: "Kalaallisut",
  },
  {
    code: "km",
    EnglishName: "Cambodian",
    direction: "ltr",
    localName: "ភាសាខ្មែរ",
  },
  {
    code: "kn",
    EnglishName: "Kannada",
    direction: "ltr",
    localName: "ಕನ್ನಡ",
  },
  {
    code: "khw",
    EnglishName: "Khowar",
    direction: "rtl",
    localName: "کھوار",
  },
  {
    code: "ko",
    EnglishName: "Korean",
    direction: "ltr",
    localName: "한국어",
  },
  {
    code: "kr",
    EnglishName: "Kanuri",
    direction: "ltr",
    localName: "Kanuri",
  },
  {
    code: "ks",
    EnglishName: "Kashmiri",
    direction: "rtl",
    localName: "कॉशुर / کٲشُر",
  },
  {
    code: "ksh",
    EnglishName: "Ripuarian",
    direction: "ltr",
    localName: "Ripoarisch",
  },
  {
    code: "ku",
    EnglishName: "Kurdish (Kurmanji)",
    direction: "ltr",
    localName: "Kurdî",
  },
  {
    code: "kv",
    EnglishName: "Komi",
    direction: "ltr",
    localName: "Коми",
  },
  {
    code: "kw",
    EnglishName: "Cornish",
    direction: "ltr",
    localName: "Kernewek",
  },
  {
    code: "ky",
    EnglishName: "Kirghiz",
    direction: "ltr",
    localName: "Kırgızca / Кыргызча",
  },
  {
    code: "la",
    EnglishName: "Latin",
    direction: "ltr",
    localName: "Latina",
  },
  {
    code: "lad",
    EnglishName: "Ladino / Judeo-Spanish",
    direction: "ltr",
    localName: "Dzhudezmo / Djudeo-Espanyol",
  },
  {
    code: "lan",
    EnglishName: "Lango",
    direction: "ltr",
    localName: "Leb Lango / Luo",
  },
  {
    code: "lb",
    EnglishName: "Luxembourgish",
    direction: "ltr",
    localName: "Lëtzebuergesch",
  },
  {
    code: "lg",
    EnglishName: "Ganda",
    direction: "ltr",
    localName: "Luganda",
  },
  {
    code: "li",
    EnglishName: "Limburgian",
    direction: "ltr",
    localName: "Limburgs",
  },
  {
    code: "lij",
    EnglishName: "Ligurian",
    direction: "ltr",
    localName: "Líguru",
  },
  {
    code: "lmo",
    EnglishName: "Lombard",
    direction: "ltr",
    localName: "Lumbaart",
  },
  {
    code: "ln",
    EnglishName: "Lingala",
    direction: "ltr",
    localName: "Lingála",
  },
  {
    code: "lo",
    EnglishName: "Laotian",
    direction: "ltr",
    localName: "ລາວ / Pha xa lao",
  },
  {
    code: "lzz",
    EnglishName: "Laz",
    direction: "ltr",
    localName: "Lazuri / ლაზური",
  },
  {
    code: "lt",
    EnglishName: "Lithuanian",
    direction: "ltr",
    localName: "Lietuvių",
  },
  {
    code: "lv",
    EnglishName: "Latvian",
    direction: "ltr",
    localName: "Latviešu",
  },
  {
    code: "map-bms",
    EnglishName: "Banyumasan",
    direction: "ltr",
    localName: "Basa Banyumasan",
  },
  {
    code: "mg",
    EnglishName: "Malagasy",
    direction: "ltr",
    localName: "Malagasy",
  },
  {
    code: "man",
    EnglishName: "Mandarin",
    direction: "ltr",
    localName: "官話/官话",
  },
  {
    code: "mh",
    EnglishName: "Marshallese",
    direction: "ltr",
    localName: "Kajin Majel / Ebon",
  },
  {
    code: "mi",
    EnglishName: "Māori",
    direction: "ltr",
    localName: "Māori",
  },
  {
    code: "min",
    EnglishName: "Minangkabau",
    direction: "ltr",
    localName: "Minangkabau",
  },
  {
    code: "mk",
    EnglishName: "Macedonian",
    direction: "ltr",
    localName: "Македонски",
  },
  {
    code: "ml",
    EnglishName: "Malayalam",
    direction: "ltr",
    localName: "മലയാളം",
  },
  {
    code: "mn",
    EnglishName: "Mongolian",
    direction: "ltr",
    localName: "Монгол",
  },
  {
    code: "mo",
    EnglishName: "Moldovan",
    direction: "ltr",
    localName: "Moldovenească",
  },
  {
    code: "mr",
    EnglishName: "Marathi",
    direction: "ltr",
    localName: "मराठी",
  },
  {
    code: "mrh",
    EnglishName: "Mara",
    direction: "ltr",
    localName: "Mara",
  },
  {
    code: "ms",
    EnglishName: "Malay",
    direction: "ltr",
    localName: "Bahasa Melayu",
  },
  {
    code: "mt",
    EnglishName: "Maltese",
    direction: "ltr",
    localName: "bil-Malti",
  },
  {
    code: "mus",
    EnglishName: "Creek / Muskogee",
    direction: "ltr",
    localName: "Mvskoke",
  },
  {
    code: "mwl",
    EnglishName: "Mirandese",
    direction: "ltr",
    localName: "Mirandés",
  },
  {
    code: "my",
    EnglishName: "Burmese",
    direction: "ltr",
    localName: "Myanmasa",
  },
  {
    code: "na",
    EnglishName: "Nauruan",
    direction: "ltr",
    localName: "Dorerin Naoero",
  },
  {
    code: "nah",
    EnglishName: "Nahuatl",
    direction: "ltr",
    localName: "Nahuatl",
  },
  {
    code: "nap",
    EnglishName: "Neapolitan",
    direction: "ltr",
    localName: "Nnapulitano",
  },
  {
    code: "nd",
    EnglishName: "North Ndebele",
    direction: "ltr",
    localName: "Sindebele",
  },
  {
    code: "nds",
    EnglishName: "Low German / Low Saxon",
    direction: "ltr",
    localName: "Plattdüütsch",
  },
  {
    code: "nds-nl",
    EnglishName: "Dutch Low Saxon",
    direction: "ltr",
    localName: "Nedersaksisch",
  },
  {
    code: "ne",
    EnglishName: "Nepali",
    direction: "ltr",
    localName: "नेपाली",
  },
  {
    code: "new",
    EnglishName: "Newar",
    direction: "ltr",
    localName: "नेपालभाषा / Newah Bhaye",
  },
  {
    code: "ng",
    EnglishName: "Ndonga",
    direction: "ltr",
    localName: "Oshiwambo",
  },
  {
    code: "nl",
    EnglishName: "Dutch",
    direction: "ltr",
    localName: "Nederlands",
  },
  {
    code: "nn",
    EnglishName: "Norwegian Nynorsk",
    direction: "ltr",
    localName: "Norsk (nynorsk)",
  },
  {
    code: "no",
    EnglishName: "Norwegian",
    direction: "ltr",
    localName: "Norsk (bokmål / riksmål)",
  },
  {
    code: "nr",
    EnglishName: "South Ndebele",
    direction: "ltr",
    localName: "isiNdebele",
  },
  {
    code: "nso",
    EnglishName: "Northern Sotho",
    direction: "ltr",
    localName: "Sesotho sa Leboa / Sepedi",
  },
  {
    code: "nrm",
    EnglishName: "Norman",
    direction: "ltr",
    localName: "Nouormand / Normaund",
  },
  {
    code: "nv",
    EnglishName: "Navajo",
    direction: "ltr",
    localName: "Diné bizaad",
  },
  {
    code: "ny",
    EnglishName: "Chichewa",
    direction: "ltr",
    localName: "Chi-Chewa",
  },
  {
    code: "oc",
    EnglishName: "Occitan",
    direction: "ltr",
    localName: "Occitan",
  },
  {
    code: "oj",
    EnglishName: "Ojibwa",
    direction: "ltr",
    localName: "ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin",
  },
  {
    code: "om",
    EnglishName: "Oromo",
    direction: "ltr",
    localName: "Oromoo",
  },
  {
    code: "or",
    EnglishName: "Oriya",
    direction: "ltr",
    localName: "ଓଡ଼ିଆ",
  },
  {
    code: "os",
    EnglishName: "Ossetian / Ossetic",
    direction: "ltr",
    localName: "Иронау",
  },
  {
    code: "pa",
    EnglishName: "Panjabi / Punjabi",
    direction: "ltr",
    localName: "ਪੰਜਾਬੀ / پنجابی",
  },
  {
    code: "pag",
    EnglishName: "Pangasinan",
    direction: "ltr",
    localName: "Pangasinan",
  },
  {
    code: "pam",
    EnglishName: "Kapampangan",
    direction: "ltr",
    localName: "Kapampangan",
  },
  {
    code: "pap",
    EnglishName: "Papiamentu",
    direction: "ltr",
    localName: "Papiamentu",
  },
  {
    code: "pdc",
    EnglishName: "Pennsylvania German",
    direction: "ltr",
    localName: "Deitsch",
  },
  {
    code: "pi",
    EnglishName: "Pali",
    direction: "ltr",
    localName: "Pāli / पाऴि",
  },
  {
    code: "pih",
    EnglishName: "Norfolk",
    direction: "ltr",
    localName: "Norfuk",
  },
  {
    code: "pl",
    EnglishName: "Polish",
    direction: "ltr",
    localName: "Polski",
  },
  {
    code: "pms",
    EnglishName: "Piedmontese",
    direction: "ltr",
    localName: "Piemontèis",
  },
  {
    code: "ps",
    EnglishName: "Pashto",
    direction: "rtl",
    localName: "پښتو",
  },
  {
    code: "pt",
    EnglishName: "Portuguese",
    direction: "ltr",
    localName: "Português",
  },
  {
    code: "qu",
    EnglishName: "Quechua",
    direction: "ltr",
    localName: "Runa Simi",
  },
  {
    code: "rm",
    EnglishName: "Raeto Romance",
    direction: "ltr",
    localName: "Rumantsch",
  },
  {
    code: "rmy",
    EnglishName: "Romani",
    direction: "ltr",
    localName: "Romani / रोमानी",
  },
  {
    code: "rn",
    EnglishName: "Kirundi",
    direction: "ltr",
    localName: "Kirundi",
  },
  {
    code: "ro",
    EnglishName: "Romanian",
    direction: "ltr",
    localName: "Română",
  },
  {
    code: "roa-rup",
    EnglishName: "Aromanian",
    direction: "ltr",
    localName: "Armâneashti",
  },
  {
    code: "ru",
    EnglishName: "Russian",
    direction: "ltr",
    localName: "Русский",
  },
  {
    code: "rw",
    EnglishName: "Rwandi",
    direction: "ltr",
    localName: "Kinyarwandi",
  },
  {
    code: "sa",
    EnglishName: "Sanskrit",
    direction: "ltr",
    localName: "संस्कृतम्",
  },
  {
    code: "sc",
    EnglishName: "Sardinian",
    direction: "ltr",
    localName: "Sardu",
  },
  {
    code: "scn",
    EnglishName: "Sicilian",
    direction: "ltr",
    localName: "Sicilianu",
  },
  {
    code: "sco",
    EnglishName: "Scots",
    direction: "ltr",
    localName: "Scots",
  },
  {
    code: "sd",
    EnglishName: "Sindhi",
    direction: "rtl",
    localName: "सिंधी / سنڌي‎",
  },
  {
    code: "se",
    EnglishName: "Northern Sami",
    direction: "ltr",
    localName: "Davvisámegiella",
  },
  {
    code: "sg",
    EnglishName: "Sango",
    direction: "ltr",
    localName: "Sängö",
  },
  {
    code: "sh",
    EnglishName: "Serbo-Croatian",
    direction: "ltr",
    localName: "Srpskohrvatski / Српскохрватски",
  },
  {
    code: "si",
    EnglishName: "Sinhalese",
    direction: "ltr",
    localName: "සිංහල",
  },
  {
    code: "simple",
    EnglishName: "Simple English",
    direction: "ltr",
    localName: "Simple English",
  },
  {
    code: "sk",
    EnglishName: "Slovak",
    direction: "ltr",
    localName: "Slovenčina",
  },
  {
    code: "sl",
    EnglishName: "Slovenian",
    direction: "ltr",
    localName: "Slovenščina",
  },
  {
    code: "sm",
    EnglishName: "Samoan",
    direction: "ltr",
    localName: "Gagana Samoa",
  },
  {
    code: "sn",
    EnglishName: "Shona",
    direction: "ltr",
    localName: "chiShona",
  },
  {
    code: "so",
    EnglishName: "Somalia",
    direction: "ltr",
    localName: "Soomaaliga",
  },
  {
    code: "sq",
    EnglishName: "Albanian",
    direction: "ltr",
    localName: "Shqip",
  },
  {
    code: "sr",
    EnglishName: "Serbian",
    direction: "ltr",
    localName: "Српски",
  },
  {
    code: "ss",
    EnglishName: "Swati",
    direction: "ltr",
    localName: "SiSwati",
  },
  {
    code: "st",
    EnglishName: "Southern Sotho",
    direction: "ltr",
    localName: "Sesotho",
  },
  {
    code: "su",
    EnglishName: "Sundanese",
    direction: "ltr",
    localName: "Basa Sunda",
  },
  {
    code: "sv",
    EnglishName: "Swedish",
    direction: "ltr",
    localName: "Svenska",
  },
  {
    code: "sw",
    EnglishName: "Swahili",
    direction: "ltr",
    localName: "Kiswahili",
  },
  {
    code: "ta",
    EnglishName: "Tamil",
    direction: "ltr",
    localName: "தமிழ்",
  },
  {
    code: "te",
    EnglishName: "Telugu",
    direction: "ltr",
    localName: "తెలుగు",
  },
  {
    code: "tet",
    EnglishName: "Tetum",
    direction: "ltr",
    localName: "Tetun",
  },
  {
    code: "tg",
    EnglishName: "Tajik",
    direction: "ltr",
    localName: "Тоҷикӣ",
  },
  {
    code: "th",
    EnglishName: "Thai",
    direction: "ltr",
    localName: "ไทย / Phasa Thai",
  },
  {
    code: "ti",
    EnglishName: "Tigrinya",
    direction: "ltr",
    localName: "ትግርኛ",
  },
  {
    code: "tk",
    EnglishName: "Turkmen",
    direction: "ltr",
    localName: "Туркмен / تركمن",
  },
  {
    code: "tl",
    EnglishName: "Tagalog",
    direction: "ltr",
    localName: "Tagalog / ᜆᜄᜎᜓᜄ᜔",
  },
  {
    code: "tlh",
    EnglishName: "Klingon",
    direction: "ltr",
    localName: "tlhIngan-Hol",
  },
  {
    code: "tn",
    EnglishName: "Tswana",
    direction: "ltr",
    localName: "Setswana",
  },
  {
    code: "to",
    EnglishName: "Tonga",
    direction: "ltr",
    localName: "Lea Faka-Tonga",
  },
  {
    code: "tpi",
    EnglishName: "Tok Pisin",
    direction: "ltr",
    localName: "Tok Pisin",
  },
  {
    code: "tr",
    EnglishName: "Turkish",
    direction: "ltr",
    localName: "Türkçe",
  },
  {
    code: "ts",
    EnglishName: "Tsonga",
    direction: "ltr",
    localName: "Xitsonga",
  },
  {
    code: "tt",
    EnglishName: "Tatar",
    direction: "ltr",
    localName: "Tatarça",
  },
  {
    code: "tum",
    EnglishName: "Tumbuka",
    direction: "ltr",
    localName: "chiTumbuka",
  },
  {
    code: "tw",
    EnglishName: "Twi",
    direction: "ltr",
    localName: "Twi",
  },
  {
    code: "ty",
    EnglishName: "Tahitian",
    direction: "ltr",
    localName: "Reo Mā`ohi",
  },
  {
    code: "udm",
    EnglishName: "Udmurt",
    direction: "ltr",
    localName: "Удмурт кыл",
  },
  {
    code: "ug",
    EnglishName: "Uyghur",
    direction: "ltr",
    localName: "Uyƣurqə / ئۇيغۇرچە",
  },
  {
    code: "uk",
    EnglishName: "Ukrainian",
    direction: "ltr",
    localName: "Українська",
  },
  {
    code: "ur",
    EnglishName: "Urdu",
    direction: "rtl",
    localName: "اردو",
  },
  {
    code: "uz",
    EnglishName: "Uzbek",
    direction: "ltr",
    localName: "Ўзбек",
  },
  {
    code: "uz_AF",
    EnglishName: "Uzbeki Afghanistan",
    direction: "rtl",
    localName: "اوزبیکی",
  },
  {
    code: "ve",
    EnglishName: "Venda",
    direction: "ltr",
    localName: "Tshivenḓa",
  },
  {
    code: "vi",
    EnglishName: "Vietnamese",
    direction: "ltr",
    localName: "Tiếng Việt",
  },
  {
    code: "vec",
    EnglishName: "Venetian",
    direction: "ltr",
    localName: "Vèneto",
  },
  {
    code: "vls",
    EnglishName: "West Flemish",
    direction: "ltr",
    localName: "West-Vlaoms",
  },
  {
    code: "vo",
    EnglishName: "Volapük",
    direction: "ltr",
    localName: "Volapük",
  },
  {
    code: "wa",
    EnglishName: "Walloon",
    direction: "ltr",
    localName: "Walon",
  },
  {
    code: "war",
    EnglishName: "Waray / Samar-Leyte Visayan",
    direction: "ltr",
    localName: "Winaray / Binisaya Lineyte-Samarnon",
  },
  {
    code: "wo",
    EnglishName: "Wolof",
    direction: "ltr",
    localName: "Wollof",
  },
  {
    code: "xal",
    EnglishName: "Kalmyk",
    direction: "ltr",
    localName: "Хальмг",
  },
  {
    code: "xh",
    EnglishName: "Xhosa",
    direction: "ltr",
    localName: "isiXhosa",
  },
  {
    code: "xmf",
    EnglishName: "Megrelian",
    direction: "ltr",
    localName: "მარგალური",
  },
  {
    code: "yi",
    EnglishName: "Yiddish",
    direction: "rtl",
    localName: "ייִדיש",
  },
  {
    code: "yo",
    EnglishName: "Yoruba",
    direction: "ltr",
    localName: "Yorùbá",
  },
  {
    code: "za",
    EnglishName: "Zhuang",
    direction: "ltr",
    localName: "Cuengh / Tôô / 壮语",
  },
  {
    code: "zh",
    EnglishName: "Chinese",
    direction: "ltr",
    localName: "中文",
  },
  {
    code: "zh-classical",
    EnglishName: "Classical Chinese",
    direction: "ltr",
    localName: "文言",
  },
  {
    code: "zh-min-nan",
    EnglishName: "Minnan",
    direction: "ltr",
    localName: "Bân-lâm-gú",
  },
  {
    code: "zh-yue",
    EnglishName: "Cantonese",
    direction: "ltr",
    localName: "粵語 / 粤语",
  },
  {
    code: "zu",
    EnglishName: "Zulu",
    direction: "ltr",
    localName: "isiZulu",
  },
];
